# Generated by Django 4.2.5 on 2023-09-09 09:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", jsonfield.fields.JSONField()),
            ],
        ),
    ]
