# Generated by Django 4.2.5 on 2023-09-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demonstrationapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FutureRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("close", models.FloatField()),
                ("sma01", models.FloatField()),
                ("sma02", models.FloatField()),
                ("sma03", models.FloatField()),
            ],
        ),
    ]
